### ISSUE TITLE
Install command doesn't give script permission before executing

### ISSUE THREAD

**Issue by bhav97** [denysdovhan/oceanic-next-gnome-terminal#1]
Changing

`wget https://raw.githubusercontent.com/denysdovhan/oceanic-next-gnome-terminal/master/oceanic-next.sh && . oceanic-next.sh`

to

`wget https://raw.githubusercontent.com/denysdovhan/oceanic-next-gnome-terminal/master/oceanic-next.sh && chmod +x oceanic-next.sh && ./oceanic-next.sh`

works.

Thanks

**Comment by denysdovhan** [comment]
@Bhav97 fixed. Thanks!
