### ISSUE TITLE
installation information ubuntu update

### ISSUE THREAD

**Issue by smhg** [denysdovhan/oceanic-next-gnome-terminal#4]
As mentioned in #1, the installation method isn't working (at least on Ubuntu 18.04 LTS).

This fixed it for me:
```bash
wget https://raw.githubusercontent.com/denysdovhan/oceanic-next-gnome-terminal/master/oceanic-next.bash && chmod +x oceanic-next.bash && ./oceanic-next.bash
```
It is the same as in #1, except the script's extension is now `bash`.

**Comment by smhg** [comment]
@denysdovhan is it ok for you to change this?
I'm happy to send a PR.

**Comment by denysdovhan** [comment]
@smhg okay, go ahead. I'm happy to merge.
